[book]
title = "The LFE Tutorial"
author = "Robert Virding and Duncan McGreggor"
description = "Getting Started with LFE"
language = "en"

[build]
build-dir = "docs"

[preprocessor.index]

[preprocessor.links]

[output.html]
additional-css = ["css/custom.css"]
google-analytics = "UA-38274766-4"
git-repository-url = "https://github.com/lfe/tutorial/"
[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 2
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2
